image: gmantaos/defold:latest
stages:
  - build

# test:
#   script:
#   - npm i

build-web:
  type: deploy
  stage: build
  script:
  - bob -h
  - echo "----------------------"
  - echo "Running bob.jar - resolving dependencies"
  - bob -auth yada --email yada@yada resolve
  - echo "Running bob.jar - building"
  - bob build bundle -p js-web -br report.json
  - mv build public
  - ls -lah
#   only:
#   - dev
  artifacts:
    paths:
    - report.json
    - public

# production:
#   type: deploy
#   stage: production
#   script:
#   - gem install dpl
#   - dpl --provider=heroku --app=kondr1 --api-key=$HEROKU_API_KEY
#   only:
#   - master
