image: gmantaos/defold:latest
stages:
  - build

# test:
#   script:
#   - npm i

build-web:
  type: deploy
  stage: build
  script:
  - echo "Running bob.jar - resolving dependencies"
  - bob -auth yada --email yada@yada resolve
  - echo "Running bob.jar - build"
  - bob build --archive -br report-build.json
  - echo "Running bob.jar - bundle"
  - bob bundle -p js-web --bundle-output bundle -br report-bundle.json
  - mv bundle/platform public
  - ls -lah
#   only:
#   - dev
  artifacts:
    paths:
    - report-*.json
    - public

# production:
#   type: deploy
#   stage: production
#   script:
#   - gem install dpl
#   - dpl --provider=heroku --app=kondr1 --api-key=$HEROKU_API_KEY
#   only:
#   - master
