stages:
  - build
  - deploy

build-web:
  image: gmantaos/defold:latest
  stage: build
  script:
  - bob --version
  - echo "Running bob - resolving dependencies"
  - bob resolve -auth yada --email yada@yada
  - echo "Running bob - build"
  - bob build --archive -br report-build.json
  - echo "Running bob - bundle"
  - bob bundle -p js-web --bundle-output bundle
  - ls -lah
  artifacts:
    paths:
    - report-*.json
    - build
    - bundle
    
pages:
  stage: deploy
  script:
  - mv bundle/platform public
  artifacts:
    paths:
    - public
