stages:
  - build
  - deploy

build-web:
  image: gmantaos/defold:latest
  stage: build
  script:
  - echo bob --version
  - echo "Running bob.jar - resolving dependencies"
  - bob -auth yada --email yada@yada resolve
  - echo "Running bob.jar - build"
  - bob build --archive -br report-build.json
  - echo "Running bob.jar - bundle"
  - bob bundle -p js-web --bundle-output bundle
  - ls -lah
  artifacts:
    paths:
    - report-*.json
    - bundle
    
pages:
  stage: deploy
  script:
  - mv bundle/platform public
  artifacts:
    paths:
    - public
